06/17/2022 09:43:57

diff --git a/.github/workflows/action.yaml b/.github/workflows/action.yaml
--- a/.github/workflows/action.yaml
+++ b/.github/workflows/action.yaml
@@ -10,41 +10,53 @@ jobs:
   test_build_job:
 
     runs-on: ubuntu-latest
+
     steps:
-      - name: info
-        run: echo "The name of branch is ${{ github.ref }} repository is ${{ github.repository }}."
-
-      - name: Checkout the repository
-        uses: actions/checkout@v3
-
-      - name: List files in the repository
-        run: |
-          ls ${{ github.workspace }}
-
-      - name: Set up JDK 14
+      - uses: actions/checkout@v3
+      - name: Set up JDK 11
         uses: actions/setup-java@v3
         with:
-          java-version: '14'
+          java-version: '11'
           distribution: 'adopt'
           cache: maven
+      - name: Build with Maven
+        run: mvn --batch-mode --update-snapshots verify
 
-      - name: Build with maven
-        run: mvn --batch-mode --update-snapshots -DskipTests package
-
-      - name: Test
-        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
-
-      - name: Test report
-        uses: dorny/test-reporter@v1
-        with:
-          artifact: test-results
-          name: JEST Tests
-          path: '*.xml'
-          reporter: jest-junit
-
-      - name: Upload
-        uses: actions/upload-artifact@v3
-        if: success() || failure()
-        with:
-          name: test-results
-          path: jest-junit.xml
+    # steps:
+    #   - name: info
+    #     run: echo "The name of branch is ${{ github.ref }} repository is ${{ github.repository }}."
+    #
+    #   - name: Checkout the repository
+    #     uses: actions/checkout@v3
+    #
+    #   - name: List files in the repository
+    #     run: |
+    #       ls ${{ github.workspace }}
+    #
+    #   - name: Set up JDK 14
+    #     uses: actions/setup-java@v3
+    #     with:
+    #       java-version: '14'
+    #       distribution: 'adopt'
+    #       cache: maven
+    #
+    #   - name: Build with maven
+    #     run: mvn --batch-mode --update-snapshots --file=pom.xml -DskipTests package
+    #
+    #   - name: Test
+    #     run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
+    #
+    #   - name: Test report
+    #     uses: dorny/test-reporter@v1
+    #     with:
+    #       artifact: test-results
+    #       name: JEST Tests
+    #       path: '*.xml'
+    #       reporter: jest-junit
+    #
+    #   - name: Upload
+    #     uses: actions/upload-artifact@v3
+    #     if: success() || failure()
+    #     with:
+    #       name: test-results
+    #       path: jest-junit.xml
